# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04
    
    env:
      SPARK_LOCAL_IP: localhost
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark
    - name: Run test cases
      run: |
        java -version
        spark-submit ./tests/test_dummy.py > ./tests/target/reports.txt
    - name: Upload test results to report
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name : "test_results"
          path: "./tests/target/reports.txt"
